{{- if .Values.albIngress.enabled -}}
{{- $fullName := include "docker-template.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $allHosts := .Values.albIngress.hosts -}}
{{- $customPaths := .Values.albIngress.custom_paths -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "docker-template.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: alb
    {{- if .Values.albIngress.group_name }}
    alb.ingress.kubernetes.io/group.name: {{ .Values.albIngress.group_name }}
    {{- end }}
    alb.ingress.kubernetes.io/scheme: {{ .Values.albIngress.scheme }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    {{- if .Values.albIngress.certificate_arn }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.albIngress.certificate_arn }}
    {{- end }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.albIngress.target_type }}
    {{- if .Values.albIngress.security_groups }}
    alb.ingress.kubernetes.io/security-groups: {{ .Values.albIngress.security_groups }}
    {{- end }}
    {{- if .Values.albIngress.healthcheck_port }}
    alb.ingress.kubernetes.io/healthcheck-port: {{ .Values.albIngress.healthcheck_port }}
    {{- end }}
    {{- if .Values.albIngress.healthcheck_protocol }}
    alb.ingress.kubernetes.io/healthcheck-protocol: {{ .Values.albIngress.healthcheck_protocol }}
    {{- end }}
spec:
  rules:
  {{- range $allHosts }}
    - host: {{ . | quote }}
      http:
        paths:
          {{ if gt (len $customPaths) 0 }}
          {{- range $customPaths }}
          - path: {{ .path }}
            {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: ImplementationSpecific
            {{- end }}
            backend:
            {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              service:
                name: {{ .serviceName }}
                port:
                  number: {{ .servicePort }}
            {{- else }}
              serviceName: {{ .serviceName }} 
              servicePort: {{ .servicePort }}
            {{- end }}
          {{- end }}
          {{ else }}
          - path: /*
            {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: ImplementationSpecific
            {{- end }}
            backend:
            {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
            {{- else }}
              serviceName: {{ $fullName }} 
              servicePort: {{ $svcPort }}
            {{- end }}
          {{- end }}
  {{- end }}        
{{- end }}
