{{- if and (ne .Values.image.repository "public.ecr.aws/o1j4x7p4/hello-porter-job") (not .Values.paused) -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-{{ randAlphaNum 10 | lower }}"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    {{- if .Values.retainFailedHooks }}
    "helm.sh/hook-delete-policy": hook-succeeded
    {{- else }}
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    {{- end }}
spec:
  backoffLimit: 0
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      serviceAccountName: {{ include "docker-template.fullname" . }}
      restartPolicy: Never
      containers:
      - name: job-manager
        image: public.ecr.aws/o1j4x7p4/job-manager:latest
        imagePullPolicy: Always
        args:
        - "create"
        env:
        - name: JOB_TEMPLATE_PATH
          value: /porter/manifest/manifest.yaml
        - name: LABEL_SELECTOR
          value: {{ printf "%s=%s" "meta.helm.sh/release-name" .Release.Name  }}
        - name: ALLOW_CONCURRENCY
          value: {{ .Values.allowConcurrency | quote }}
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 32Mi
        volumeMounts:
        - name: manifest-data
          mountPath: /porter/manifest
      {{- if gt (len .Values.nodeSelector) 0}}
      nodeSelector:
        {{- range $k, $v := .Values.nodeSelector }}
        {{ $k }}: {{ $v }}
        {{- end }}
      {{- end }}
      tolerations:
        - key: "removable"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      volumes:
      - name: manifest-data
        configMap:
          name: {{ include "docker-template.fullname" . }}
          items:
            - key: manifest
              path: manifest.yaml
{{ end }}
